//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webddac2017.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Flightbooking
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Field Required")]
        public string Passenger_Name { get; set; }
        [Required(ErrorMessage = "Field Required")]
        public string Flight_Location { get; set; }
        [Required(ErrorMessage = "Field Required")]
        public string Flight_Destination { get; set; }
        [Required(ErrorMessage = "Field Required")]
        public string Flight_Time { get; set; }
        [Required(ErrorMessage = "Field Required")]
        public string Class { get; set; }
        [Required(ErrorMessage = "Field Required")]
        public string Seat { get; set; }
        //[Required(ErrorMessage = "Field Required")]
        public string Gate { get; set; }
        [Required(ErrorMessage = "Field Required")]
        public string Date { get; set; }
    }
}
