//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webddac2017.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel; // Confirm Password Box
    using System.ComponentModel.DataAnnotations; // Validation for DataType and Password Mask

    public partial class User
    {
        public int UserID { get; set; }
        [Required(ErrorMessage = "Field Required")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Field Required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Required(ErrorMessage = "Field Required")]
        [DataType(DataType.Password)]
        [DisplayName("Confirm Password")]
        [Compare("Password")]
        public string ConfirmPassword { get; set; }
        [Required(ErrorMessage = "Field Required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Field Required")]
        public Nullable<int> Contact { get; set; }
        [Required(ErrorMessage = "Field Required")]
        public string Email { get; set; }
    }

    public partial class UserLogin
    {
        [Required(ErrorMessage = "Field Required")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Field Required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public string ErrorMessageLogin { get; set; }
    }
}
